import Button from "components/ui/Button";
import { useWeb3ConnectWindow } from "components/ui/WalletConnectWindow";
import { useWeb3Wallet } from "hooks/useWeb3";
import type { NextPage } from "next";
import Head from "next/head";

const Admin: NextPage = () => {
  const wallet = useWeb3Wallet();
  const walletConnect = useWeb3ConnectWindow();

  return (
    <div>
      <Head>
        <title>Melegend Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button
          text="Connect"
          onClick={() => {
            walletConnect.connect();
          }}
        />
      </main>
    </div>
  );
};

export default Admin;
